============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/esau/desarrolloDeSoftware/proyectos/Prueba_entrada_CC3S2/seccion2_python_git
plugins: cov-4.1.0
collected 0 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_app.py ______________________
ImportError while importing test module '/home/esau/desarrolloDeSoftware/proyectos/Prueba_entrada_CC3S2/seccion2_python_git/tests/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_app.py:2: in <module>
    from app.app import summarize
E   ModuleNotFoundError: No module named 'app'

---------- coverage: platform linux, python 3.12.3-final-0 -----------
Name              Stmts   Miss  Cover   Missing
-----------------------------------------------
app/__init__.py       0      0   100%
app/app.py           25     25     0%   7-33
-----------------------------------------------
TOTAL                25     25     0%

=========================== short test summary info ============================
ERROR tests/test_app.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.10s ===============================
