============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.3, pluggy-1.6.0
rootdir: /home/esau/desarrolloDeSoftware/labs/Laboratorio3
configfile: pytest.ini
plugins: Faker-37.8.0, cov-5.0.0
collected 15 items

tests/test_carrito.py .........                                          [ 60%]
tests/test_shopping_cart.py ......                                       [100%]

=============================== warnings summary ===============================
venv_labo3/lib/python3.12/site-packages/_pytest/config/__init__.py:1500
  /home/esau/desarrolloDeSoftware/labs/Laboratorio3/venv_labo3/lib/python3.12/site-packages/_pytest/config/__init__.py:1500: PytestConfigWarning: No files were found in testpaths; consider removing or adjusting your testpaths configuration. Searching recursively from the current directory instead.
    self.args, self.args_source = self._decide_args(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.12.3-final-0 -----------
Name                   Stmts   Miss  Cover   Missing
----------------------------------------------------
src/__init__.py            0      0   100%
src/carrito.py            55      7    87%   9, 21, 50, 52, 60, 68, 91
src/factories.py           7      0   100%
src/shopping_cart.py      29      3    90%   9, 27, 31
----------------------------------------------------
TOTAL                     91     10    89%

======================== 15 passed, 1 warning in 0.13s =========================
